on:
    push:
      branches:
        - main

jobs:
    test-docker-image:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build Docker image
              run: docker build -t risk-assessments:latest .

            - name: Run Docker container
              run: docker run -d -p 3000:80 --name risk-assessments-container risk-assessments:latest

            - name: Test Docker container is running
              run: |
                if [ "$(docker ps -q -f name=risk-assessments-container)" = "" ]; then
                  echo "Container is not running"
                  exit 1
                else
                  echo "Container is running"
                fi

            - name: Test that we get a 200 response from the application
              run: |
                RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000)
                if [ "$RESPONSE" -ne 200 ]; then
                  echo "Expected HTTP 200 but got $RESPONSE"
                  exit 1
                else
                  echo "Received expected HTTP 200 response"
                fi

            - name: Test content, look for the "https://blacksmithinfosec.com" string in the footer of the homepage
              run: |
                CONTENT=$(curl -s http://localhost:3000)
                if [[ "$CONTENT" != *"https://blacksmithinfosec.com"* ]]; then
                  echo "Expected content not found in the homepage"
                  exit 1
                else
                  echo "Expected content found in the homepage"
                fi

            - name: Clean up
              run: |